// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/accounts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/accounts/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/accounts/index.post').default>>>>
    }
    '/accounts/new': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/accounts/new/index.post').default>>>>
    }
    '/budgets/charts/usage': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/budgets/charts/usage/index.get').default>>>>
    }
    '/budgets': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/budgets/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/budgets/index.post').default>>>>
    }
    '/budgets/missing': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/budgets/missing/index.get').default>>>>
    }
    '/carousel': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/carousel/index.get').default>>>>
    }
    '/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/categories/index.get').default>>>>
    }
    '/is-account-setup-complete': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/is-account-setup-complete/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/is-account-setup-complete/index.post').default>>>>
    }
    '/ping': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/ping/index.get').default>>>>
    }
    '/prompts': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/prompts/index.get').default>>>>
    }
    '/transactions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/transactions/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/transactions/index.post').default>>>>
    }
    '/transactions/manual': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/transactions/manual/index.post').default>>>>
    }
    '/transactions/stats': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/transactions/stats/index.get').default>>>>
    }
  }
}
export {}